spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: local

management:
  endpoints:
    web:
      exposure:
        include: "*"

---
spring.profiles: docker
spring:
  data.mongodb:
    host: mongo
    port: 27017
    database: local